# Generated by Django 3.1.2 on 2020-11-29 15:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qr_bar_decoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 15, 31, 51, 654561, tzinfo=utc), verbose_name='Published Date'),
        ),
    ]
