# Generated by Django 3.1.2 on 2020-12-03 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qr_bar_decoder', '0013_auto_20201202_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='list',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 7, 55, 25, 884509, tzinfo=utc), verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='section',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 7, 55, 25, 885472, tzinfo=utc), verbose_name='Published Date'),
        ),
    ]
