# Generated by Django 3.1.2 on 2021-01-06 01:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qr_bar_decoder', '0014_auto_20201203_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default=datetime.datetime(2021, 1, 6, 1, 2, 51, 484134, tzinfo=utc), max_length=255),
        ),
        migrations.AlterField(
            model_name='list',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 1, 2, 51, 483134, tzinfo=utc), verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='section',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 1, 2, 51, 483134, tzinfo=utc), verbose_name='Published Date'),
        ),
    ]
